DROP TABLE IF EXISTS _t.vozilo_imp CASCADE;
DROP TABLE IF EXISTS _t.vozilo_imp_gas CASCADE;
DROP TABLE IF EXISTS _t.vozilo_imp_gu CASCADE;
DROP TABLE IF EXISTS _t.vozilo_imp_srt0 CASCADE;
DROP TABLE IF EXISTS _t.vozilo_imp_srt1 CASCADE;
DROP TABLE IF EXISTS _t.vozilo_imp_srt2 CASCADE;
COMMIT;
